### ISSUE TITLE
How to configure the extension when the test suite is in another directory ?

### ISSUE THREAD

**Issue by lyrixx** [dvdoug/behat-code-coverage#10]
The project I'm working on has the following shape (I simplified it):

```
├── projects
│   ├── api
│   ├── backend
│   ├── cdn
│   ├── common-lib
│   ├── frontend
│   └── worker
├── tests
│   ├── behat.yml
│   ├── features
```

How can I tell this extension that the code is in `../projects/*/src` ?

---

Note: I tried the following configuration, but the coverage is always 0% (but files are good)

```yaml
        DVDoug\Behat\CodeCoverage\Extension:
            filter:
                include:
                    directories:
                        '../projects/*/src/': ~
```

---

Thanks
