### ISSUE TITLE
Has no coverage for application code

### ISSUE THREAD

**Issue by ScreamingDev** [dvdoug/behat-code-coverage#11]
The application has one simple feature file:

```
Feature: Foo
  Szenario: Bar
    Given I am on the homepage
```

This succeeds and runs all the code in the file "src/index.php". But the following Behat configuration does not measure the application coverage:

```
    DVDoug\Behat\CodeCoverage\Extension:
      filter:
        include:
          directories:
            'src': ~
      reports:
        html:
          target: "tmp/behat/coverage"
```

It is missing the connection between Behat and the actual code that runs.
Is there a solution for that?

If not, then please consider adding a "bootstrap.php"-like file that could be included in the actual application. Such file could measure the actual coverage for each time the application is run during the test.
